# Generated by Django 5.0.7 on 2024-08-21 22:13

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('pub_text', tinymce.models.HTMLField(verbose_name='publications')),
                ('pub_title', models.CharField(max_length=100, verbose_name='publication title')),
                ('pub_image', models.ImageField(null=True, upload_to='publications/', verbose_name='publication image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publications',
            },
        ),
    ]
